# Generated by Django 4.1.7 on 2024-08-05 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/posts/%Y/%m/%d')),
            ],
        ),
    ]
