# Generated by Django 5.0.7 on 2024-08-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_style',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('Gavin', 'Gavin'), ('Asinia', 'Asinia')], default='Gavin', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Recent events', 'Recent events'), ('Future plans', 'Future plans'), ('Our memoires', 'Our memories')], default='Recent events', max_length=50),
        ),
    ]
