# Generated by Django 5.0.7 on 2024-08-06 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tag1_post_tag2_post_tag3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_style',
        ),
    ]
