# Generated by Django 5.0.7 on 2024-08-06 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('post', models.IntegerField(default=0)),
            ],
        ),
    ]
