# Generated by Django 5.0.7 on 2024-08-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_wish_date_alter_wish_name_alter_wish_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GRE', 'GRE')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
