# Generated by Django 5.0.7 on 2024-08-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.CharField(choices=[('GRE', 'GRE'), ('Other', 'Other')], max_length=50),
        ),
    ]
